CREATE DATABASE ELECTRONICS;
USE ELECTRONICS;
SELECT * FROM PRODUCT ORDER BY CAST(SUBSTRING(P_ID, 2,LEN(P_ID) - 1 ) AS INT);
SELECT * FROM PURCHASE ORDER BY CAST(SUBSTRING(USER_ID, 2,LEN(USER_ID) - 1 ) AS INT);
SELECT * FROM Users ORDER BY CAST(SUBSTRING(USER_ID, 2,LEN(USER_ID) - 1 ) AS INT);

----Q1----
SELECT CATEGORY, AVG(RATING) AS Avg_Rating
    FROM Product
    GROUP BY CATEGORY;

----Q2----
SELECT RATING
    FROM Product;

----Q3----
SELECT TIMESTAMP, COUNT(*) AS Purchase_Count
    FROM Purchase
    GROUP BY TIMESTAMP;

----Q4----
SELECT CATEGORY, RATING
    FROM Product;

----Q5----
SELECT MONTH, COUNT(*) AS Purchase_Count
    FROM Purchase
    GROUP BY MONTH ORDER BY MONTH;

----Q6----
SELECT BRAND, RATING
    FROM Product;

----Q7----
SELECT P.RATING, U.USER_ATTR
    FROM Product P
    INNER JOIN Purchase PU ON P.P_ID = PU.P_ID
    INNER JOIN Users U ON PU.USER_ID = U.USER_ID;

----Q8----
SELECT RATING, CATEGORY, BRAND
    FROM Product;

----Q9----
SELECT P.RATING, PU.TIMESTAMP
    FROM Product P
    INNER JOIN Purchase PU ON P.P_ID = PU.P_ID;

----Q10----
SELECT CATEGORY, COUNT(*) AS Category_Count
    FROM Product
    GROUP BY CATEGORY;

----Q11----
SELECT TIMESTAMP, AVG(RATING) AS Avg_Rating
    FROM Purchase PU
    INNER JOIN Product P ON PU.P_ID = P.P_ID
    GROUP BY TIMESTAMP;

----Q12----
SELECT BRAND, RATING
    FROM Product;
